strictPeerDependencies: true
packages:
  - "packages/*"

catalog:
  react: ^18
  react-dom: ^18
  "@types/react": ^18
  "@types/react-dom": ^18

  "@docusaurus/core": 3.9.2
  "@docusaurus/preset-classic": 3.9.2
  "@docusaurus/module-type-aliases": 3.9.2
  "@docusaurus/plugin-content-blog": 3.9.2
  "@docusaurus/plugin-content-docs": 3.9.2
  "@docusaurus/plugin-content-pages": 3.9.2
  "@docusaurus/theme-classic": 3.9.2
  "@docusaurus/theme-common": 3.9.2
  "@docusaurus/types": 3.9.2
  "@docusaurus/utils-validation": 3.9.2
